version: '3.8'
volumes:
  postgres-data: { }
services:
  movies-api:
    #build: .
    image: andica92/movies-api:latest
    depends_on:
      - database
    ports:
      - "8080:8080"
    restart: on-failure
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: on-failure
    environment:
      POSTGRES_USER: movie
      POSTGRES_PASSWORD: movie
